#' Class to store loopQTL input data and analysis results
#'
#' loopQTL objects should normally be generated by `loopQTLsetup()`. See its
#' documentation for more information on the expected format of input data.
#'
#' All slots can also be accessed through an identically named function, i.e.,
#' to access `results(obj)`, use `loopQTL::results(obj)`.
#'
#' @slot samples List of unique sample IDs
#' @slot loops Consensus intra-chromosomal loops as a
#'   [InteractionSet::GInteractions] object
#' @slot cis Optional numeric vector of per-sample cis-contact totals. Must
#'   have names matching the IDs in `samples`, and be in the same order as
#'   `samples`.
#' @slot vcfPath Path to the tabix-indexed VCF
#' @slot resolution Analysis bin size (bp)
#' @slot phenotype Matrix containing normalized numeric phenotype data for each
#'   loop (in the rows) and each sample (in the columns). Dimensions and order
#    must equal those of `loops` and `samples`. Empty if `loopQTLnormalize()`
#'   has not been run.
#' @slot results QTL result table. Empty if `runQTL()` has not been run.
#'   Contains a row for each loop-SNP pair and columns `loopID`, `snpID`,
#'   `chrom`, `pos`, `ref`, `alt`, `anchor`, `beta`, `se`, `t`, `p`, `nUsed`,
#'   and `maf`. If `loopQTLannotate()` has been run, also contains `gene`,
#'   `peak` (optional), and `Type` columns.
#' @slot metadata Function-specific metadata
#'
#' @name loopQTL-class
#' @aliases samples loops cis vcfPath resolution phenotype results metadata
#' @exportClass loopQTL
#' @seealso loopQTLsetup
#' @examples
#' obj <- loopQTLExampleData()
#' obj
#' samples(obj)
#' loops(obj)
setClass(
    "loopQTL",
    representation(
        samples = "character",
        loops = "GInteractions",
        cis = "numeric",
        vcfPath = "character",
        resolution = "integer",
        phenotype = "matrix",
        results = "data.frame",
        metadata = "list"
    ),
    prototype(
        samples = character(0),
        loops = InteractionSet::GInteractions(),
        cis = numeric(0),
        vcfPath = NA_character_,
        resolution = NA_integer_,
        phenotype = matrix(numeric(0), 0, 1),
        results = data.frame(),
        metadata = list()
    )
)

setValidity("loopQTL", function(object) {
    ## For some reason, annoyingly, the length of "" is 1, so we
    ## use character(0) instead
    errs <- character(0)

    ## Also annoyingly, the length of NA is 1
    if (.isSingleNA(object@samples) || length(object@samples) == 0) {
        errs <- c(errs, "samples must be non-empty")
    }

    if (anyDuplicated(object@samples)) {
        errs <- c(errs, "samples must be unique")
    }

    if (length(object@cis) > 0) {
        if (length(object@cis) != length(object@samples) ||
            !identical(names(object@cis), object@samples)) {
            errs <- c(
                errs,
                "names(cis) must be equal to and in the same order as samples"
            )
        }
    }

    if (length(object@phenotype) > 0) {
        if (!identical(colnames(object@phenotype), object@samples)) {
            errs <- c(errs, paste(
                "colnames(phenotype) must be equal to and in",
                "the same order as samples"
            ))
        }
        if (nrow(object@phenotype) != length(object@loops)) {
            errs <- c(errs, "phenotype must have one row per loop")
        }
    }

    if (length(errs) > 0) {
        message(errs)
        return(errs)
    }
    return(TRUE)
})

setGeneric("samples", function(object) standardGeneric("samples"))
setGeneric("loops", function(object) standardGeneric("loops"))
setGeneric("cis", function(object) standardGeneric("cis"))
setGeneric("vcfPath", function(object) standardGeneric("vcfPath"))
setGeneric("resolution", function(object) standardGeneric("resolution"))
setGeneric("phenotype", function(object) standardGeneric("phenotype"))
setGeneric("results", function(object) standardGeneric("results"))
setGeneric("metadata", function(object) standardGeneric("metadata"))

#' @rdname loopQTL-class
#' @param object a loopQTL object
#' @export
setMethod("samples", "loopQTL", function(object) {
    return(object@samples)
})

#' @rdname loopQTL-class
#' @param object a loopQTL object
#' @export
setMethod("loops", "loopQTL", function(object) {
    return(object@loops)
})

#' @rdname loopQTL-class
#' @param object a loopQTL object
#' @export
setMethod("cis", "loopQTL", function(object) {
    return(object@cis)
})

#' @rdname loopQTL-class
#' @param object a loopQTL object
#' @export
setMethod("vcfPath", "loopQTL", function(object) {
    return(object@vcfPath)
})

#' @rdname loopQTL-class
#' @param object a loopQTL object
#' @export
setMethod("resolution", "loopQTL", function(object) {
    return(object@resolution)
})

#' @rdname loopQTL-class
#' @param object a loopQTL object
#' @export
setMethod("phenotype", "loopQTL", function(object) {
    return(object@phenotype)
})

#' @rdname loopQTL-class
#' @param object a loopQTL object
#' @export
setMethod("results", "loopQTL", function(object) {
    return(object@results)
})

#' @rdname loopQTL-class
#' @param object a loopQTL object
#' @export
setMethod("metadata", "loopQTL", function(object) {
    return(object@metadata)
})

#' @rdname loopQTL-class
#' @param object a loopQTL object
#' @export
setMethod("show", "loopQTL", function(object) {
    cat("loopQTL object:\n")
    cat(
        "\tsamples   :", length(object@samples),
        "(", paste(utils::head(object@samples, 4), collapse = ", "),
        if (length(object@samples) > 4) ", ..." else "", ")\n"
    )
    cat(
        "\tloops     :", length(object@loops),
        "consensus intra-chromosomal loops\n"
    )
    cat("\tresolution:", object@resolution, "bp\n")
    cat(
        "\tphenotype :",
        if (length(object@phenotype) > 0) {
            paste(nrow(object@phenotype), "x", ncol(object@phenotype), "matrix")
        } else {
            "not yet computed"
        }, "\n"
    )
    cat(
        "\tresults   :",
        if (nrow(object@results) > 0) {
            paste(nrow(object@results), "loop-SNP pairs")
        } else {
            "not yet computed"
        }, "\n"
    )
    if (length(object@metadata) > 0) {
        cat("\tmeta      :\n")
        for (nm in names(object@metadata)) {
            cat(
                "\t\t", nm, "=", paste(object@metadata[[nm]], collapse = ", "),
                "\n"
            )
        }
    }
    invisible(NULL)
})
